name: CI

on: [push]

jobs:
  composer:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - uses: php-actions/composer@v5

      - name: Archive build
        run: mkdir /tmp/github-actions/ && tar -cvf /tmp/github-actions/build.tar ./

      - name: Upload build archive for test runners
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: /tmp/github-actions

  phpunit:
    runs-on: ubuntu-latest
    needs: [composer]

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: build-artifact
          path: /tmp/github-actions

      - name: Extract build archive
        run: tar -xvf /tmp/github-actions/build.tar ./

      - name: PHP Unit tests
        uses: php-actions/phpunit@v2
        with:
          php_version: 8.0
          php_extensions: xdebug
          configuration: test/phpunit/phpunit.xml
          bootstrap: vendor/autoload.php

  phpstan:
    runs-on: ubuntu-latest
    needs: [composer]

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: build-artifact
          path: /tmp/github-actions

      - name: Extract build archive
        run: tar -xvf /tmp/github-actions/build.tar ./

      - name: PHP Static Analysis
        uses: php-actions/phpstan@v2
        with:
          path: src/
